import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/app/ui/header/header';
import './globals.css';

export const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased min-h-screen`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
